= Asciidoctor Documentation
:description: Index page listing AsciiDoc and Asciidoctor documents and resources including the Asciidoctor User Manual, AsciiDoc Quick Reference Guide, the benefits of AsciiDoc, the benefits of Asciidoctor, Asciidoctor Installation Guide, How to Convert an AsciiDoc document, and Asciidoctor Developer Resources.
:keywords: Asciidoctor, AsciiDoc, documentation, user manual, cheatsheet, ref card, AsciiDoc versus Markdown, Asciidoctor versus Markdown, install
:page-layout: docs
:page-description: {description}
:page-keywords: {keywords}
:rainbow-themes: pass:quotes[[red]##t##[green]##h##[purple]##e##[fuchsia]##m##[blue]##e##[teal]##s##]
:toc:


Follow the links on this page to learn about the AsciiDoc markup language, Asciidoctor toolchain and the Asciidoctor integrations.
You'll also find tips on how to be most productive when writing with the AsciiDoc syntax.

TIP: Can't find the information you need? Reach out to project members and users via the https://discuss.asciidoctor.org/[discussion list] or the https://gitter.im/asciidoctor/asciidoctor[asciidoctor/asciidoctor Gitter channel].

== The Basics

Discover Asciidoctor and how it can help you.

* link:what-is-asciidoctor/[What is Asciidoctor?]

* link:what-is-asciidoc-why-use-it/[What is AsciiDoc? Why do we need it?]

* link:asciidoc-asciidoctor-diffs/[How do Asciidoctor and AsciiDoc differ?]

* link:/#authors[Who created Asciidoctor?]

* https://github.com/asciidoctor/asciidoctor/blob/master/LICENSE[What is the Asciidoctor license?]

* link:asciidoc-vs-markdown/[How do AsciiDoc and Markdown differ?]

* http://www.vogella.com/tutorials/AsciiDoc/article.html[Using AsciiDoc and Asciidoctor to write documentation] (article by vogella)

== Get Started with Asciidoctor

Now, let's setup and use the Asciidoctor toolchain!

* link:install-toolchain/[How do I install the Asciidoctor toolchain?]
+
[sidebar]
.Using macOS?
Follow the guide link:install-asciidoctor-macos/[Installing Asciidoctor on macOS] for an in-depth tutorial.

```java
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * @author Darren Rambaud (10/20/20)
 * <p>
 * darren@rambaud.io
 */
public class App {
    public static void main(String[] args) {
    }
}
```